export const data = [
    {
        id: 349,
        "parent-id": 250,
        type: "Town",
        name: "İstanbul Avrupa",
        "geo-location": {
            latitude: 41.0620024,
            longitude: 28.8913871,
            zoom: 12,
        },
        zoom: 12,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 1,
        "reference-code": "tr",
        "city-id": 250,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "fatih beyoglu besiktas kadikoy uskudar sariyer esenler silivri arnavutkoy ese esen esenl ali alibeykoy alibey ist Bağcılar Otobüs Kalkış-Varış Noktası Esenler Otogarı Alibeyköy Sefaköy Gültepe Sanayi Mah. İstanbul Havalimanı Gazi Mahallesi Küçükçekmece Fatih Çatalca Halıcıoğlu Palmiye Kanarya Cevatpaşa Mecidiyekoy Küçükköy Balat Terminali Firuzköy Bakırköy Kağıthane Üçyüzlü Beşyüzevler 4.Levent Avcılar Bahçelievler Büyükçekmece Eyüp Ömür Plaza Esenyurt Balıkyolu Bayrampaşa Şişli Beşiktaş Yıldız Camii Okmeydanı Zeytinburnu Yenikapı İdo Silahtar Noıktası Şirinevler Halkalı İncirli Kıraç Kalkış - Varış Aksaray Atatürk Bulvarı Emniyet (İstanbul)",
        "city-name": "İstanbul",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "İstanbul Avrupa - İstanbul",
        "is-city-center": false,
    },
    {
        id: 350,
        "parent-id": 250,
        type: "Town",
        name: "İstanbul Anadolu",
        "geo-location": {
            latitude: 41.0051554250553,
            longitude: 29.0662292542803,
            zoom: 12,
        },
        zoom: 12,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 2,
        "reference-code": "tr",
        "city-id": 250,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "fatih beyoglu besiktas kadikoy uskudar sariyer bolu yalova gebze izmit sakarya adapazari sapanca bursa gerede altinova ana anna ist Ataşehir Dudullu İsmail Ayaz Tesisleri Truva Terminali Nilüfer Pamukkale Tepeüstü Otobüs Kalkış-Varış Noktası Ortadağ Kartal Samandıra Servis Taşlıbayır Kayışdağı Yenidoğan Maltepe Göztepe İçmeler Kadıköy (İstanbul) Pendik Esatpaşa Kavacık Harem Otogarı Sultanbeyli Koşuyolu Bostancı Emek Güzelyalı Kurtköy Kozyatağı Tuzla Sarıgazi Cevizli Sabiha Gökçen Harmandere Rıhtım Ferhatpaşa Sancaktepe Köprü Ümraniye Üsküdar Yenisahra Kaynarca",
        "city-name": "İstanbul",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "İstanbul Anadolu - İstanbul",
        "is-city-center": false,
    },
    {
        id: 356,
        "parent-id": 222,
        type: "Town",
        name: "Ankara",
        "geo-location": {
            latitude: 39.911652,
            longitude: 32.840305,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 3,
        "reference-code": "tr",
        "city-id": 222,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "aşti aşt asti ast abka Pursaklar Otobüs Kalkış-Varış Noktası Ankara (Aşti) Otogarı (Söğütözü) Cep Terminali Yol Gimat (Ankara) Temelli Söğütözü",
        "city-name": "Ankara",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Ankara",
        "is-city-center": false,
    },
    {
        id: 383,
        "parent-id": 251,
        type: "Town",
        name: "İzmir",
        "geo-location": {
            latitude: 38.412726,
            longitude: 27.138376,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 4,
        "reference-code": "tr",
        "city-id": 251,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "gevrek aLiBeY İzmir Adnan Menderes Havalimanı Otogar Tesis Otobüs Kalkış-Varış Noktası Ege Üniversitesi Kalkış Varış Evka 3 Manavkuyu Otogarı Bornova Hareket Merkezi Egs Park",
        "city-name": "İzmir",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "İzmir",
        "is-city-center": false,
    },
    {
        id: 348,
        "parent-id": 217,
        type: "Town",
        name: "Adana",
        "geo-location": {
            latitude: 37.001667,
            longitude: 35.328889,
            zoom: 12,
        },
        zoom: 12,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 5,
        "reference-code": "tr",
        "city-id": 217,
        "reference-country": null,
        "country-id": 8,
        keywords: "adana Adana Otogarı Yüreğir",
        "city-name": "Adana",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Adana",
        "is-city-center": false,
    },
    {
        id: 366,
        "parent-id": 232,
        type: "Town",
        name: "Bursa",
        "geo-location": {
            latitude: 40.18223,
            longitude: 29.05493,
            zoom: 13,
        },
        zoom: 13,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 6,
        "reference-code": "tr",
        "city-id": 232,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "Bursa Otogarı Uludağ Üniv. Otobüs Kalkış-Varış Noktası Kent Meydanı Küçükbalıklı Emek (Bursa) Vatan Mah. Fakülte Mahallesi Millet",
        "city-name": "Bursa",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Bursa",
        "is-city-center": false,
    },
    {
        id: 357,
        "parent-id": 223,
        type: "Town",
        name: "Antalya",
        "geo-location": {
            latitude: 36.908118,
            longitude: 30.695565,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 7,
        "reference-code": "tr",
        "city-id": 223,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "Hal Kavşağı Otobüs Kalkış-Varış Noktası Barınaklar Opet Antalya İlçeler Terminali Havalimanı Pınarlı Otogarı Aktur Park",
        "city-name": "Antalya",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Antalya",
        "is-city-center": false,
    },
    {
        id: 376,
        "parent-id": 242,
        type: "Town",
        name: "Eskişehir",
        "geo-location": {
            latitude: 39.776667,
            longitude: 30.520556,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 8,
        "reference-code": "tr",
        "city-id": 242,
        "reference-country": null,
        "country-id": 8,
        keywords: "Eskişehir Otogarı",
        "city-name": "Eskişehir",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Eskişehir",
        "is-city-center": false,
    },
    {
        id: 389,
        "parent-id": 258,
        type: "Town",
        name: "Konya",
        "geo-location": {
            latitude: 37.871354,
            longitude: 32.484636,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 9,
        "reference-code": "tr",
        "city-id": 258,
        "reference-country": null,
        "country-id": 8,
        keywords: "Konya Otogarı Eski Garaj(Merkez) Tren İstasyonu",
        "city-name": "Konya",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Konya",
        "is-city-center": false,
    },
    {
        id: 382,
        "parent-id": 249,
        type: "Town",
        name: "Mersin",
        "geo-location": {
            latitude: 36.80628,
            longitude: 34.63992,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 10,
        "reference-code": "tr",
        "city-id": 249,
        "reference-country": null,
        "country-id": 8,
        keywords: "içel Mersin Otogarı Otogar Kavşağı Otobüs Kalkış - Varış Noktası Eski Tece (Mersin) Kalkış-Varış",
        "city-name": "Mersin",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Mersin",
        "is-city-center": false,
    },
    {
        id: 352,
        "parent-id": 218,
        type: "Town",
        name: "Adıyaman",
        "geo-location": {
            latitude: 37.76441,
            longitude: 38.276287,
            zoom: 9,
        },
        zoom: 9,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 20,
        "reference-code": "tr",
        "city-id": 218,
        "reference-country": null,
        "country-id": 8,
        keywords: "Adıyaman Otogarı",
        "city-name": "Adıyaman",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Adıyaman",
        "is-city-center": false,
    },
    {
        id: 353,
        "parent-id": 219,
        type: "Town",
        name: "Afyon",
        "geo-location": {
            latitude: 38.75680044719131,
            longitude: 30.537352606665973,
            zoom: 13,
        },
        zoom: 13,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 20,
        "reference-code": "tr",
        "city-id": 219,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "ayf ayfo Afyon Otogarı Tesis Otobüs Kalkış-Varış Noktası Afyon(Cumhuriyet) Eski Otogar Kolaylı Dinlenme Tesisleri İstikbal (Afyon)",
        "city-name": "Afyon",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Afyon",
        "is-city-center": false,
    },
    {
        id: 354,
        "parent-id": 220,
        type: "Town",
        name: "Ağrı",
        "geo-location": {
            latitude: 39.714666,
            longitude: 43.040151,
            zoom: 8,
        },
        zoom: 8,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 20,
        "reference-code": "tr",
        "city-id": 220,
        "reference-country": null,
        "country-id": 8,
        keywords: "Ağrı Otogarı",
        "city-name": "Ağrı",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Ağrı",
        "is-city-center": false,
    },
    {
        id: 414,
        "parent-id": 284,
        type: "Town",
        name: "Aksaray",
        "geo-location": {
            latitude: 38.37255,
            longitude: 34.02537,
            zoom: 12,
        },
        zoom: 12,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 20,
        "reference-code": "tr",
        "city-id": 284,
        "reference-country": null,
        "country-id": 8,
        keywords: "Aksaray Otogarı Eski Garaj Otobüs Kalkış-Varış Noktası Ağaçlı Tesisleri",
        "city-name": "Aksaray",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Aksaray",
        "is-city-center": false,
    },
    {
        id: 355,
        "parent-id": 221,
        type: "Town",
        name: "Amasya",
        "geo-location": {
            latitude: 40.653333,
            longitude: 35.833056,
            zoom: 13,
        },
        zoom: 13,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 20,
        "reference-code": "tr",
        "city-id": 221,
        "reference-country": null,
        "country-id": 8,
        keywords: "Amasya Yampaş Otobüs Kalkış-Varış Noktası Otogarı Park Avm Yeni Otogar",
        "city-name": "Amasya",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Amasya",
        "is-city-center": false,
    },
    {
        id: 421,
        "parent-id": 291,
        type: "Town",
        name: "Ardahan",
        "geo-location": {
            latitude: 41.108711,
            longitude: 42.702222,
            zoom: 14,
        },
        zoom: 14,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 20,
        "reference-code": "tr",
        "city-id": 291,
        "reference-country": null,
        "country-id": 8,
        keywords: "Aşıkşenlik Ardahan Otogarı",
        "city-name": "Ardahan",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Ardahan",
        "is-city-center": false,
    },
    {
        id: 358,
        "parent-id": 224,
        type: "Town",
        name: "Artvin",
        "geo-location": {
            latitude: 41.181611,
            longitude: 41.821722,
            zoom: 14,
        },
        zoom: 14,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 20,
        "reference-code": "tr",
        "city-id": 224,
        "reference-country": null,
        "country-id": 8,
        keywords: "Artvin Otogarı",
        "city-name": "Artvin",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Artvin",
        "is-city-center": false,
    },
    {
        id: 359,
        "parent-id": 225,
        type: "Town",
        name: "Aydın",
        "geo-location": {
            latitude: 37.845008,
            longitude: 27.839626,
            zoom: 9,
        },
        zoom: 9,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 20,
        "reference-code": "tr",
        "city-id": 225,
        "reference-country": null,
        "country-id": 8,
        keywords: "Aydın Otogarı",
        "city-name": "Aydın",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Aydın",
        "is-city-center": false,
    },
    {
        id: 360,
        "parent-id": 226,
        type: "Town",
        name: "Balıkesir",
        "geo-location": {
            latitude: 39.649167,
            longitude: 27.886111,
            zoom: 13,
        },
        zoom: 13,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 20,
        "reference-code": "tr",
        "city-id": 226,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "Yıldız Mola Tesisleri Otobüs Kalkış-Varış Noktası Ekbir Dinlenme Balıkesir Yonca Otogarı Kuvayi Milliye Gazi Bulvarı Toplu Taşıma Merkezi İdo",
        "city-name": "Balıkesir",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Balıkesir",
        "is-city-center": false,
    },
    {
        id: 420,
        "parent-id": 290,
        type: "Town",
        name: "Bartın",
        "geo-location": {
            latitude: 41.635833,
            longitude: 32.3375,
            zoom: 13,
        },
        zoom: 13,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 20,
        "reference-code": "tr",
        "city-id": 290,
        "reference-country": null,
        "country-id": 8,
        keywords: "Bartın Otogarı Tekkeönü Otobüs Kalkış-Varış Noktası",
        "city-name": "Bartın",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Bartın",
        "is-city-center": false,
    },
];
export const locations = [
    {
        id: 349,
        "parent-id": 250,
        type: "Town",
        name: "İstanbul Avrupa",
        "geo-location": {
            latitude: 41.0620024,
            longitude: 28.8913871,
            zoom: 12,
        },
        zoom: 12,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 1,
        "reference-code": "tr",
        "city-id": 250,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "fatih beyoglu besiktas kadikoy uskudar sariyer esenler silivri arnavutkoy ese esen esenl ali alibeykoy alibey ist Bayrampaşa Otobüs Kalkış-Varış Noktası Üçyüzlü Beşyüzevler Kanarya Esenler Otogarı Alibeyköy Cevatpaşa Halıcıoğlu Palmiye Ömür Plaza Esenyurt Balıkyolu Beşiktaş Yıldız Camii Terminali Firuzköy 4.Levent Avcılar Bahçelievler Büyükçekmece Eyüp Gültepe İstanbul Havalimanı Sanayi Mah. Bakırköy Kağıthane Şişli Küçükçekmece Sefaköy Bağcılar Çatalca Fatih Mecidiyekoy Balat Küçükköy Kalkış - Varış Aksaray Atatürk Bulvarı Halkalı Şirinevler İncirli Kıraç Okmeydanı Zeytinburnu Yenikapı İdo Gazi Mahallesi Silahtar Noıktası Emniyet (İstanbul)",
        "city-name": "İstanbul",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "İstanbul Avrupa - İstanbul",
        "is-city-center": false,
    },
    {
        id: 350,
        "parent-id": 250,
        type: "Town",
        name: "İstanbul Anadolu",
        "geo-location": {
            latitude: 41.0051554250553,
            longitude: 29.0662292542803,
            zoom: 12,
        },
        zoom: 12,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 2,
        "reference-code": "tr",
        "city-id": 250,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "fatih beyoglu besiktas kadikoy uskudar sariyer bolu yalova gebze izmit sakarya adapazari sapanca bursa gerede altinova ana anna ist Ataşehir Dudullu İsmail Ayaz Tesisleri Truva Terminali Nilüfer Pamukkale Kadıköy Rıhtım Otobüs Kalkış-Varış Noktası İçmeler Ferhatpaşa Sancaktepe Göztepe Maltepe Kozyatağı Samandıra Servis Taşlıbayır Kayışdağı Kartal Ortadağ Kurtköy Tepeüstü Cevizli Sarıgazi Tuzla Sabiha Gökçen Yenisahra Ümraniye Üsküdar Kavacık Köprü Pendik Otogarı Emek Yenidoğan (İstanbul) Esatpaşa Harem Harmandere Sultanbeyli Kaynarca Koşuyolu Bostancı Güzelyalı",
        "city-name": "İstanbul",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "İstanbul Anadolu - İstanbul",
        "is-city-center": false,
    },
    {
        id: 356,
        "parent-id": 222,
        type: "Town",
        name: "Ankara",
        "geo-location": {
            latitude: 39.911652,
            longitude: 32.840305,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 3,
        "reference-code": "tr",
        "city-id": 222,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "aşti aşt asti ast abka Ankara (Aşti) Otogarı (Söğütözü) Cep Terminali Yol Otobüs Kalkış-Varış Noktası Gimat (Ankara) Söğütözü Pursaklar Temelli",
        "city-name": "Ankara",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Ankara",
        "is-city-center": false,
    },
    {
        id: 383,
        "parent-id": 251,
        type: "Town",
        name: "İzmir",
        "geo-location": {
            latitude: 38.412726,
            longitude: 27.138376,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 4,
        "reference-code": "tr",
        "city-id": 251,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "gevrek aLiBeY İzmir Adnan Menderes Havalimanı Bornova Hareket Merkezi Otobüs Kalkış-Varış Noktası Egs Park Otogarı Ege Üniversitesi Kalkış Varış Otogar Tesis Evka 3 Manavkuyu",
        "city-name": "İzmir",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "İzmir",
        "is-city-center": false,
    },
    {
        id: 348,
        "parent-id": 217,
        type: "Town",
        name: "Adana",
        "geo-location": {
            latitude: 37.001667,
            longitude: 35.328889,
            zoom: 12,
        },
        zoom: 12,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 5,
        "reference-code": "tr",
        "city-id": 217,
        "reference-country": null,
        "country-id": 8,
        keywords: "adana Yüreğir Otogarı Adana",
        "city-name": "Adana",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Adana",
        "is-city-center": false,
    },
    {
        id: 366,
        "parent-id": 232,
        type: "Town",
        name: "Bursa",
        "geo-location": {
            latitude: 40.18223,
            longitude: 29.05493,
            zoom: 13,
        },
        zoom: 13,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 6,
        "reference-code": "tr",
        "city-id": 232,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "Bursa Otogarı Uludağ Üniv. Otobüs Kalkış-Varış Noktası Kent Meydanı Emek (Bursa) Vatan Mah. Küçükbalıklı Mahallesi Fakülte Millet",
        "city-name": "Bursa",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Bursa",
        "is-city-center": false,
    },
    {
        id: 357,
        "parent-id": 223,
        type: "Town",
        name: "Antalya",
        "geo-location": {
            latitude: 36.908118,
            longitude: 30.695565,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 7,
        "reference-code": "tr",
        "city-id": 223,
        "reference-country": null,
        "country-id": 8,
        keywords:
            "Barınaklar Opet Otobüs Kalkış-Varış Noktası Havalimanı Pınarlı Antalya Terminali Otogarı Hal Kavşağı İlçeler Aktur Park",
        "city-name": "Antalya",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Antalya",
        "is-city-center": false,
    },
    {
        id: 376,
        "parent-id": 242,
        type: "Town",
        name: "Eskişehir",
        "geo-location": {
            latitude: 39.776667,
            longitude: 30.520556,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 8,
        "reference-code": "tr",
        "city-id": 242,
        "reference-country": null,
        "country-id": 8,
        keywords: "Eskişehir Otogarı",
        "city-name": "Eskişehir",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Eskişehir",
        "is-city-center": false,
    },
    {
        id: 389,
        "parent-id": 258,
        type: "Town",
        name: "Konya",
        "geo-location": {
            latitude: 37.871354,
            longitude: 32.484636,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 9,
        "reference-code": "tr",
        "city-id": 258,
        "reference-country": null,
        "country-id": 8,
        keywords: "Konya Otogarı Tren İstasyonu Eski Garaj(Merkez)",
        "city-name": "Konya",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Konya",
        "is-city-center": false,
    },
    {
        id: 382,
        "parent-id": 249,
        type: "Town",
        name: "Mersin",
        "geo-location": {
            latitude: 36.80628,
            longitude: 34.63992,
            zoom: 11,
        },
        zoom: 11,
        "tz-code": "Turkey Standard Time",
        "weather-code": null,
        rank: 10,
        "reference-code": "tr",
        "city-id": 249,
        "reference-country": null,
        "country-id": 8,
        keywords: "içel Mersin Otogarı Otogar Kavşağı Otobüs Kalkış - Varış Noktası Tece (Mersin) Kalkış-Varış Eski",
        "city-name": "Mersin",
        languages: null,
        "country-name": "Türkiye",
        code: null,
        "show-country": false,
        "area-code": null,
        "long-name": "Mersin",
        "is-city-center": false,
    },
];
